name: iOS Build for TestFlight

on:
  workflow_dispatch:

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      # ----------------- SET BUILD DATE -----------------
      - uses: ./.github/actions/set-build-date

      # ----------------- SET COMMIT HASH -----------------
      - uses: ./.github/actions/set-commit-hash

      # ----------------- SETUP JAVA (required for KMP) -----------------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # ----------------- CREATE SECRETS -----------------
      - name: Create Secrets.xcconfig
        env:
          GOOGLE_CLIENT_ID_IOS: ${{ secrets.GOOGLE_CLIENT_ID_IOS }}
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cat > iosApp/Configuration/Secrets.xcconfig <<EOF
          GOOGLE_CLIENT_ID_WEB = ${GOOGLE_CLIENT_ID_IOS}
          GOOGLE_REVERSE_CLIENT_ID_WEB = com.googleusercontent.apps.$(echo ${GOOGLE_CLIENT_ID_IOS} | sed 's/.apps.googleusercontent.com//')
          EOF
          sed -i '' "s/TEAM_ID=/TEAM_ID=${TEAM_ID}/" iosApp/Configuration/Config.xcconfig

      # ----------------- INSTALL DEPENDENCIES -----------------
      - run: sudo gem install cocoapods fastlane
      - run: cd iosApp && pod install

      # ----------------- BUILD & UPLOAD -----------------
      - name: Build and upload to TestFlight
        env:
          APP_IDENTIFIER: pt.socialfood
          GIT_CERTIFICATES_URL: ${{ secrets.GIT_CERTIFICATES_URL }}
          GIT_CERTIFICATES_BRANCH: master
          MATCH_TYPE: appstore
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          KEY_FILEPATH: ${{ secrets.APPSTORE_AUTH_KEY }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          BUILD_DATE: ${{ env.BUILD_DATE }}
        run: cd iosApp && fastlane beta
